kind: Service
apiVersion: v1
metadata:
  name: demogod-service
spec:
  type: NodePort
  selector:
    app: demogod
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30036
    protocol: TCP
